export type DayKey =
  | "lundi"
  | "mardi"
  | "mercredi"
  | "jeudi"
  | "vendredi"
  | "samedi"
  | "dimanche";

export type ScheduleItem = {
  id: string;
  title: string;
  category: string;
  time: string;
  image?: string;
  accent?: string;
};

export const DAY_LABELS: { key: DayKey; label: string }[] = [
  { key: "lundi", label: "Lundi" },
  { key: "mardi", label: "Mardi" },
  { key: "mercredi", label: "Mercredi" },
  { key: "jeudi", label: "Jeudi" },
  { key: "vendredi", label: "Vendredi" },
  { key: "samedi", label: "Samedi" },
  { key: "dimanche", label: "Dimanche" },
];

export const DATE_RANGE_LABEL =
  "Lundi 30 Mars 2026 - Dimanche 5 Avril 2026";

export const DAY_DATE_LABELS: Record<DayKey, string> = {
  lundi: "Programme du Lundi 30 Mars 2026",
  mardi: "Programme du Mardi 31 Mars 2026",
  mercredi: "Programme du Mercredi 01 Avril 2026",
  jeudi: "Programme du Jeudi 02 Avril 2026",
  vendredi: "Programme du Vendredi 03 Avril 2026",
  samedi: "Programme du Samedi 04 Avril 2026",
  dimanche: "Programme du Dimanche 05 Avril 2026",
};

export const SCHEDULE_BY_DAY: Record<DayKey, ScheduleItem[]> = {
  lundi: [
    {
      id: "lu-1",
      title: "Grand format",
      category: "MAGAZINE",
      time: "06:00 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "lu-2",
      title: "L’invité",
      category: "ENTRETIEN",
      time: "07:10 GMT",
      image: "/programs/linvite-hero-mobile.jpg",
      accent: "#d9a11a",
    },
    {
      id: "lu-3",
      title: "À vous la parole",
      category: "DÉBAT",
      time: "07:50 GMT",
      image: "/programs/a-vous-la-parole-hero-mobile.jpg",
      accent: "#e21a23",
    },
    {
      id: "lu-4",
      title: "Les entretiens",
      category: "ENTRETIENS",
      time: "08:30 GMT",
      image: "/programs/les-entretiens-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "lu-5",
      title: "Le débat",
      category: "DÉBAT",
      time: "10:20 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "lu-6",
      title: "Grand format",
      category: "MAGAZINE",
      time: "13:30 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "lu-7",
      title: "Le débat",
      category: "DÉBAT",
      time: "19:00 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "lu-8",
      title: "L’intelligent club",
      category: "TALK-SHOW",
      time: "20:20 GMT",
      image: "/programs/lintelligent-club-hero-mobile.jpg",
      accent: "#2b8cff",
    },
    {
      id: "lu-9",
      title: "À vous la parole",
      category: "DÉBAT",
      time: "21:30 GMT",
      image: "/programs/a-vous-la-parole-hero-mobile.jpg",
      accent: "#e21a23",
    },
    {
      id: "lu-10",
      title: "Grand format (rediff)",
      category: "REDIFFUSION",
      time: "22:10 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
  ],

  mardi: [
    {
      id: "ma-1",
      title: "L’intelligent club",
      category: "TALK-SHOW",
      time: "06:00 GMT",
      image: "/programs/lintelligent-club-hero-mobile.jpg",
      accent: "#2b8cff",
    },
    {
      id: "ma-2",
      title: "L’invité",
      category: "ENTRETIEN",
      time: "07:10 GMT",
      image: "/programs/linvite-hero-mobile.jpg",
      accent: "#d9a11a",
    },
    {
      id: "ma-3",
      title: "Les entretiens",
      category: "ENTRETIENS",
      time: "07:50 GMT",
      image: "/programs/les-entretiens-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "ma-4",
      title: "À vous la parole",
      category: "DÉBAT",
      time: "08:30 GMT",
      image: "/programs/a-vous-la-parole-hero-mobile.jpg",
      accent: "#e21a23",
    },
    {
      id: "ma-5",
      title: "Le débat",
      category: "DÉBAT",
      time: "10:20 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "ma-6",
      title: "Grand format",
      category: "MAGAZINE",
      time: "13:30 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "ma-7",
      title: "Le débat",
      category: "DÉBAT",
      time: "19:00 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "ma-8",
      title: "Grand format",
      category: "MAGAZINE",
      time: "20:20 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "ma-9",
      title: "Les entretiens",
      category: "ENTRETIENS",
      time: "21:30 GMT",
      image: "/programs/les-entretiens-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "ma-10",
      title: "L’intelligent club (rediff)",
      category: "REDIFFUSION",
      time: "22:10 GMT",
      image: "/programs/lintelligent-club-hero-mobile.jpg",
      accent: "#2b8cff",
    },
  ],

  mercredi: [
    {
      id: "me-1",
      title: "Grand format",
      category: "MAGAZINE",
      time: "06:00 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "me-2",
      title: "À vous la parole",
      category: "DÉBAT",
      time: "07:10 GMT",
      image: "/programs/a-vous-la-parole-hero-mobile.jpg",
      accent: "#e21a23",
    },
    {
      id: "me-3",
      title: "L’invité",
      category: "ENTRETIEN",
      time: "07:50 GMT",
      image: "/programs/linvite-hero-mobile.jpg",
      accent: "#d9a11a",
    },
    {
      id: "me-4",
      title: "Les entretiens",
      category: "ENTRETIENS",
      time: "08:30 GMT",
      image: "/programs/les-entretiens-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "me-5",
      title: "Le débat",
      category: "DÉBAT",
      time: "10:20 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "me-6",
      title: "L’intelligent club",
      category: "TALK-SHOW",
      time: "13:30 GMT",
      image: "/programs/lintelligent-club-hero-mobile.jpg",
      accent: "#2b8cff",
    },
    {
      id: "me-7",
      title: "Le débat",
      category: "DÉBAT",
      time: "19:00 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "me-8",
      title: "L’intelligent club",
      category: "TALK-SHOW",
      time: "20:20 GMT",
      image: "/programs/lintelligent-club-hero-mobile.jpg",
      accent: "#2b8cff",
    },
    {
      id: "me-9",
      title: "L’invité",
      category: "ENTRETIEN",
      time: "21:30 GMT",
      image: "/programs/linvite-hero-mobile.jpg",
      accent: "#d9a11a",
    },
    {
      id: "me-10",
      title: "Grand format (rediff)",
      category: "REDIFFUSION",
      time: "22:10 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
  ],

  jeudi: [
    {
      id: "je-1",
      title: "Les entretiens",
      category: "ENTRETIENS",
      time: "06:00 GMT",
      image: "/programs/les-entretiens-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "je-2",
      title: "L’invité",
      category: "ENTRETIEN",
      time: "07:10 GMT",
      image: "/programs/linvite-hero-mobile.jpg",
      accent: "#d9a11a",
    },
    {
      id: "je-3",
      title: "À vous la parole",
      category: "DÉBAT",
      time: "07:50 GMT",
      image: "/programs/a-vous-la-parole-hero-mobile.jpg",
      accent: "#e21a23",
    },
    {
      id: "je-4",
      title: "L’intelligent club",
      category: "TALK-SHOW",
      time: "08:30 GMT",
      image: "/programs/lintelligent-club-hero-mobile.jpg",
      accent: "#2b8cff",
    },
    {
      id: "je-5",
      title: "Le débat",
      category: "DÉBAT",
      time: "10:20 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "je-6",
      title: "Grand format",
      category: "MAGAZINE",
      time: "13:30 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "je-7",
      title: "Le débat",
      category: "DÉBAT",
      time: "19:00 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "je-8",
      title: "Grand format",
      category: "MAGAZINE",
      time: "20:20 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "je-9",
      title: "À vous la parole",
      category: "DÉBAT",
      time: "21:30 GMT",
      image: "/programs/a-vous-la-parole-hero-mobile.jpg",
      accent: "#e21a23",
    },
    {
      id: "je-10",
      title: "L’intelligent club (rediff)",
      category: "REDIFFUSION",
      time: "22:10 GMT",
      image: "/programs/lintelligent-club-hero-mobile.jpg",
      accent: "#2b8cff",
    },
  ],

  vendredi: [
    {
      id: "ve-1",
      title: "Grand format",
      category: "MAGAZINE",
      time: "06:00 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "ve-2",
      title: "À vous la parole",
      category: "DÉBAT",
      time: "07:10 GMT",
      image: "/programs/a-vous-la-parole-hero-mobile.jpg",
      accent: "#e21a23",
    },
    {
      id: "ve-3",
      title: "L’invité",
      category: "ENTRETIEN",
      time: "07:50 GMT",
      image: "/programs/linvite-hero-mobile.jpg",
      accent: "#d9a11a",
    },
    {
      id: "ve-4",
      title: "Les entretiens",
      category: "ENTRETIENS",
      time: "08:30 GMT",
      image: "/programs/les-entretiens-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "ve-5",
      title: "Le débat",
      category: "DÉBAT",
      time: "10:20 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "ve-6",
      title: "L’intelligent club",
      category: "TALK-SHOW",
      time: "13:30 GMT",
      image: "/programs/lintelligent-club-hero-mobile.jpg",
      accent: "#2b8cff",
    },
    {
      id: "ve-7",
      title: "Le débat",
      category: "DÉBAT",
      time: "19:00 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "ve-8",
      title: "L’intelligent club",
      category: "TALK-SHOW",
      time: "20:20 GMT",
      image: "/programs/lintelligent-club-hero-mobile.jpg",
      accent: "#2b8cff",
    },
    {
      id: "ve-9",
      title: "Les entretiens",
      category: "ENTRETIENS",
      time: "21:30 GMT",
      image: "/programs/les-entretiens-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "ve-10",
      title: "Grand format (rediff)",
      category: "REDIFFUSION",
      time: "22:10 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
  ],

  samedi: [
    {
      id: "sa-1",
      title: "Grand format (rediff)",
      category: "REDIFFUSION",
      time: "06:00 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "sa-2",
      title: "L’invité (rediff)",
      category: "REDIFFUSION",
      time: "07:10 GMT",
      image: "/programs/linvite-hero-mobile.jpg",
      accent: "#d9a11a",
    },
    {
      id: "sa-3",
      title: "Les entretiens (rediff)",
      category: "REDIFFUSION",
      time: "07:50 GMT",
      image: "/programs/les-entretiens-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "sa-4",
      title: "À vous la parole (rediff)",
      category: "REDIFFUSION",
      time: "08:30 GMT",
      image: "/programs/a-vous-la-parole-hero-mobile.jpg",
      accent: "#e21a23",
    },
    {
      id: "sa-5",
      title: "Le débat (rediff)",
      category: "REDIFFUSION",
      time: "10:20 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "sa-6",
      title: "L’invité",
      category: "ENTRETIEN",
      time: "12:50 GMT",
      image: "/programs/linvite-hero-mobile.jpg",
      accent: "#d9a11a",
    },
    {
      id: "sa-7",
      title: "À vous la parole",
      category: "DÉBAT",
      time: "14:40 GMT",
      image: "/programs/a-vous-la-parole-hero-mobile.jpg",
      accent: "#e21a23",
    },
    {
      id: "sa-8",
      title: "Le débat",
      category: "DÉBAT",
      time: "19:00 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "sa-9",
      title: "L’intelligent club",
      category: "TALK-SHOW",
      time: "20:20 GMT",
      image: "/programs/lintelligent-club-hero-mobile.jpg",
      accent: "#2b8cff",
    },
    {
      id: "sa-10",
      title: "À vous la parole",
      category: "DÉBAT",
      time: "21:30 GMT",
      image: "/programs/a-vous-la-parole-hero-mobile.jpg",
      accent: "#e21a23",
    },
  ],

  dimanche: [
    {
      id: "di-1",
      title: "L’intelligent club (rediff)",
      category: "REDIFFUSION",
      time: "06:00 GMT",
      image: "/programs/lintelligent-club-hero-mobile.jpg",
      accent: "#2b8cff",
    },
    {
      id: "di-2",
      title: "À vous la parole (rediff)",
      category: "REDIFFUSION",
      time: "07:10 GMT",
      image: "/programs/a-vous-la-parole-hero-mobile.jpg",
      accent: "#e21a23",
    },
    {
      id: "di-3",
      title: "Les entretiens (rediff)",
      category: "REDIFFUSION",
      time: "07:50 GMT",
      image: "/programs/les-entretiens-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "di-4",
      title: "L’invité (rediff)",
      category: "REDIFFUSION",
      time: "08:30 GMT",
      image: "/programs/linvite-hero-mobile.jpg",
      accent: "#d9a11a",
    },
    {
      id: "di-5",
      title: "Le débat (rediff)",
      category: "REDIFFUSION",
      time: "10:20 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "di-6",
      title: "Les entretiens",
      category: "ENTRETIENS",
      time: "12:50 GMT",
      image: "/programs/les-entretiens-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "di-7",
      title: "L’invité",
      category: "ENTRETIEN",
      time: "14:40 GMT",
      image: "/programs/linvite-hero-mobile.jpg",
      accent: "#d9a11a",
    },
    {
      id: "di-8",
      title: "Le débat",
      category: "DÉBAT",
      time: "19:00 GMT",
      image: "/programs/le-debat-hero-mobile.jpg",
      accent: "#1fc423",
    },
    {
      id: "di-9",
      title: "Grand format",
      category: "MAGAZINE",
      time: "20:20 GMT",
      image: "/programs/la-revue-de-presse-grand-format-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
    {
      id: "di-10",
      title: "Les entretiens",
      category: "ENTRETIENS",
      time: "21:30 GMT",
      image: "/programs/les-entretiens-hero-mobile.jpg",
      accent: "#1fb7cc",
    },
  ],
};